name: operator-framework-e2e

on:
  workflow_dispatch:
  pull_request:
  push:
   branches:
   - main

jobs:
  e2e-kind:
    runs-on: ubuntu-latest
    steps:
     
    - uses: actions/checkout@v3

    - uses: actions/setup-go@v4
      with:
        go-version-file: go.mod

    - name: Run the e2e test routine
      run: go test -v ./...

    - name: Display test results
      uses: actions/github-script@v4
      with:
        script: |
          const fs = require('fs');
          const testOutput = fs.readFileSync('test_output.txt', 'utf8');
          console.log(testOutput);
      if: ${{ job.status == 'failure' }}