name: operator-framework-e2e

on:
  workflow_dispatch:
  pull_request:
  push:
   branches:
   - main

jobs:
  e2e-kind:
    runs-on: ubuntu-latest
    steps:
     
    - uses: actions/checkout@v3

    - uses: actions/setup-go@v4
      with:
        go-version-file: go.mod

    - name: Run the e2e test routine
      run: go test -v ./...